name: Publish Plof

on:
  push:
    branches: [main, canary]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 8

      - name: Setup Node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Publish
        # Use `--no-git-checks` due to how GitHub Actions checks out
        run: pnpm semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
