name: Publish Ploff

on:
  push:
    branches: [main, canary]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build the project
        run: pnpm run build

      # Bloody NPM and the stupid setup node was failing
      - name: Authenticate with Registry
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}

      - name: Publish
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ELEVATED }}
          GIT_AUTHOR_NAME: 'Ploff Release Bot'
          GIT_AUTHOR_EMAIL: 'bot-no-contact@vorillaz.com'
          GIT_COMMITTER_NAME: 'Ploff Release Bot'
          GIT_COMMITTER_EMAIL: 'bot-no-contact@vorillaz.com'
